// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Settings struct {
	Key       string           `json:"key"`
	Value     string           `json:"value"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Transactions struct {
	ID          int32            `json:"id"`
	Date        pgtype.Date      `json:"date"`
	Amount      pgtype.Numeric   `json:"amount"`
	Description string           `json:"description"`
	Type        string           `json:"type"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}
