// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteTransaction(ctx context.Context, id int32) error
	GetAllSettings(ctx context.Context) ([]Settings, error)
	GetAllTransactions(ctx context.Context) ([]Transactions, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetTransactionByID(ctx context.Context, id int32) (Transactions, error)
	GetTransactionsByDateRange(ctx context.Context, arg GetTransactionsByDateRangeParams) ([]Transactions, error)
	GetTransactionsByType(ctx context.Context, type_ string) ([]Transactions, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
